name: Check formatting, Typescript and run unit tests

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: install dependencies
        run: yarn install
      - name: check-formatting
        run: yarn prettier:check
      - name: check-typescript
        run: yarn ts:check
      - name: test-eslint
        run: yarn lint
      - name: unit-tests
        run: yarn test
